import '../../core/utils/id_generator.dart';
import '../../data/models/app_models.dart';

CharacterNote createCharacterDraft({String? campaignId}) {
  final now = DateTime.now();
  return CharacterNote(
    id: IdGenerator.create(),
    campaignIds: [
      if (campaignId != null) campaignId,
    ],
    name: '',
    playerName: '',
    ancestryOrSpecies: '',
    className: '',
    speciesRefId: '',
    classRefId: '',
    backgroundRefId: '',
    subclassName: '',
    subclassRefId: '',
    level: 1,
    background: '',
    pronouns: '',
    alignment: '',
    experiencePoints: 0,
    proficiencyBonus: 2,
    hp: 0,
    currentHp: 0,
    temporaryHp: 0,
    hitDice: '',
    deathSaveSuccesses: 0,
    deathSaveFailures: 0,
    armorClass: 10,
    armorRefId: '',
    armorName: '',
    shieldEquipped: false,
    size: 'Medium',
    speed: 30,
    initiative: 0,
    passivePerception: 10,
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    inventoryNotes: '',
    attackNotes: '',
    featureNotes: '',
    skillNotes: '',
    savingThrowNotes: '',
    personalityNotes: '',
    toolAndLanguageNotes: '',
    treasureNotes: '',
    skillProficiencies: const {},
    savingThrowProficiencies: const {},
    selectedFeatureIds: const [],
    selectedFeatIds: const [],
    selectedTraitIds: const [],
    selectedWeaponIds: const [],
    selectedArmorIds: const [],
    selectedGearIds: const [],
    selectedSpellIds: const [],
    spellcastingAbility: 'wisdom',
    coinsNotes: '',
    weapons: const [],
    armors: const [],
    gear: const [],
    treasures: const [],
    classFeatures: const [],
    speciesTraits: const [],
    feats: const [],
    toolProficiencies: const [],
    languages: const [],
    coins: const CharacterCoins(),
    training: const CharacterTraining(),
    spellcastingSetup: const CharacterSpellcastingSetup(),
    spellNotes: const [],
    createdAt: now,
    updatedAt: now,
  );
}
